In [1]:
import gymnasium as gym 
import pygame
from gymnasium import Env
from gymnasium import spaces
from gymnasium.spaces import Discrete, Box, Dict, Tuple, MultiBinary, MultiDiscrete 
import numpy as np
import random, time
import os
#from stable_baseline3.stable_baselines3.ppo import ppo
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
from stable_baselines3 import PPO, DQN
from stable_baselines3.common.env_checker import check_env
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
import torch as th
import torch.nn as nn
from torch.optim import Adam
from collections import deque
#VISITED = [255, 255, 255]
#UNVISITED = [255, 255, 0]
#PLAYER = [255, 0, 0]
print('done')

done


In [5]:
arr = np.zeros((3, 4, 5))
print(arr[0])

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [6]:
print(np.sum([[0,0,1,0,1,0,1,0,0,1,1,0,1,0,0,0],
[0,0,1,0,1,0,1,1,0,1,0,0,1,0,0,1],
[1,1,0,0,1,0,0,0,1,1,0,0,0,1,0,0],
[0,0,0,1,0,1,0,1,0,0,0,1,1,0,1,0],
[0,1,1,0,0,0,1,0,0,1,0,0,1,0,0,0],
[1,1,0,0,1,0,0,0,0,0,1,1,1,0,0,0],
[1,0,1,0,0,1,0,0,1,0,0,0,0,1,1,0],
[0,1,1,0,0,0,1,0,0,0,1,0,1,0,0,0],
[0,0,0,1,1,1,0,0,0,0,1,0,1,0,0,0],
[1,0,0,1,0,1,0,1,0,1,1,0,1,0,1,0],
[1,0,0,0,1,1,1,0,1,0,0,0,0,0,1,0],
[0,1,0,0,1,0,1,1,1,0,1,1,0,0,0,0],
[1,0,0,1,1,0,0,1,0,1,0,0,0,0,1,0],
[1,0,0,1,0,0,1,0,1,0,1,1,1,1,0,0],
[1,0,1,0,1,1,0,1,0,1,0,0,1,0,0,0],
[1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]))

96


In [3]:
print(np.power(2, 0.3))

1.2311444133449163


In [9]:
list = np.array([[1, 2], [3, 4]])
print(list.shape)
print(list[1][1])

(2, 2)
4


In [4]:
grass_data = [[0,1,1,0,1,0,1,0,0,1,1,0,1,0,1,0,1,1,0,0],
[1,1,1,0,1,0,1,1,0,1,0,0,1,0,0,1,0,1,1,0],
[1,1,0,0,1,0,0,0,1,1,0,0,0,1,0,1,0,0,1,0],
[0,0,0,1,0,1,0,1,0,0,0,1,1,0,1,0,0,0,1,0],
[0,1,1,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0],
[1,1,0,0,1,0,0,0,0,0,1,1,1,0,0,1,0,1,0,0],
[1,0,1,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0,1],
[0,1,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,0],
[0,0,0,1,1,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0],
[1,0,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,0,0],
[1,0,0,0,1,1,1,0,1,0,0,0,0,0,1,0,1,1,0,0],
[0,1,0,0,1,0,1,1,1,0,1,1,0,0,0,1,0,0,0,1],
[1,0,0,1,1,0,0,1,0,1,0,0,0,0,1,0,1,0,0,1],
[1,0,0,1,0,0,1,0,1,0,1,1,1,1,0,0,0,1,0,1],
[1,0,0,0,1,1,0,1,0,1,0,0,1,0,0,1,1,1,0,0],
[0,0,1,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0],
[1,1,1,0,0,0,1,0,0,0,0,1,1,0,1,0,0,1,1,0],
[0,0,0,1,0,0,0,1,1,1,0,0,0,1,0,0,0,0,1,0],
[0,1,0,0,1,0,1,1,0,0,0,0,1,0,0,1,1,1,0,0],
[0,1,1,0,0,1,0,0,0,1,1,1,0,1,1,1,1,0,0,0]]
walls_data = [[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1],
[0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,1,1,0,0],
[0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0],
[0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0],
[0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1],
[0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,0],
[0,0,0,1,0,1,0,1,0,1,0,0,0,0,0,1,0,0,1,0],
[0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0],
[0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,1,0,0,1,1],
[0,1,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0],
[0,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0],
[0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0],
[0,0,1,0,1,1,0,0,0,1,0,0,0,0,1,0,1,0,0,0],
[0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,1],
[0,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,1],
[0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0],
[0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,1,0,0,0,0],
[0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1],
[0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]
corners = [[0, 0], [1, 1], [1, 0], [0, 1]]

Env for DQN

In [3]:
class MowerEnv(Env):
    def __init__(self, len, render_mode = True):
        self.render_mode = render_mode
        self.len = len
        if render_mode == True:
            pygame.init()
            self.screen = pygame.display.set_mode((720, 720))
        # Actions we can up down left right
        self.action_space = Discrete(16)
        # 0=visited, 1=notvisited
        #gym.spaces.space.Space.seed(1)


        self.observation_space = Dict({'grid': Box(low=0, high=1, shape=(2,self.len,self.len), dtype=np.uint8),                       #pos, bounds, guide
                                    'all': Box(low=0, high=self.len-1, shape=(20,), dtype=np.uint8)})

        # Set length
        self.direct = [[-1, 0], [0, 1], [1, 0], [0, -1]]

    def step(self, action):
        play = [action//4, action%4]
        reward = 0
        arr = self.state['grid'][0]
        all = self.state['all']
        for j in range(2):
            # Apply action (no walls for now)
            x = all[0 + j * 10] + self.direct[play[j]][0]
            y = all[1 + j * 10] + self.direct[play[j]][1]
            if self.isValid(x, y) == 0:
                x = all[0 + j * 10]
                y = all[1 + j * 10]
            if arr[x][y] == 1:
                self.area_clear += 1
                reward = 5.0 * np.power(4, self.area_clear/self.max_area)
            else:
                reward = -0.5
                self.running_length -= 1
            arr[x][y] = 0
            all[0+j*10] = x
            all[1+j*10] = y

            # update boundries
            for i in range(4):
                all[i+2+j*10] = self.isValid(x + self.direct[i][0], y + self.direct[i][1])
            all[6+j*10], all[7+j*10], all[8+j*10], all[9+j*10] = self.leastDist(x, y)
            # Check if  done
            if self.running_length <= 0:
                done = True
                break
            else:
                done = False
            if self.finished(): #change back to self.finished()
                reward = self.max_area * 20
                done = True
        # Set placeholder for info
        info = {}

        # Return step information
        return (self.state, reward, done, False, info)

    def isValid(self, x, y):
        if x < 0 or x < 0 or x >= self.len or y < 0 or y >= self.len:
            return 0 #return False
        if self.state['grid'][1][x][y] == 1:
            return 0
        return 1 #return true

    def leastDist(self, x, y):
        arr = self.state['grid'][0]
        up = right = down = left = 0
        done = False
        for i in range(1, 11):
            for j in range(-i, i+1):
                k = i - abs(j)
                if x + j >=0 and x + j < self.len and y + k < self.len:
                    if arr[x+j][y+k] == 1:
                        done = True
                        down = max(int(k > 0), down)
                        left = max(int(j < 0), left)
                        right = max(int(j > 0), right)
                if x + j >=0 and x + j < self.len and y - k >=0:
                    if arr[x+j][y-k] == 1:
                        done = True
                        up = max(int(k > 0), up)
                        left = max(int(j < 0), left)
                        right = max(int(j > 0), right)
            if done:
                break
        return (up, right, down, left)

    def finished(self):
        return self.area_clear==self.max_area

    def render(self):
        # Implement viz
        if self.render_mode == True:
            pygame.event.get()
            gap = 720//self.len
            arr = self.state['grid'][0]
            pos = self.state['all']
            walls = self.state['grid'][1]
            for i in range(0, 720, gap):
                for j in range(0, 720, gap):
                    if arr[i//gap][j//gap] == 0:
                        color = (255, 255, 255)
                    elif arr[i//gap][j//gap] == 1:
                        color = (255, 255,0)
                    if (i//gap == pos[0] and j//gap == pos[1]) or (i//gap == pos[10] and j//gap == pos[11]):
                        color = (255, 0, 0)
                    if walls[i//gap][j//gap] == 1:
                        color = (0, 0, 0)
                    pygame.draw.rect(self.screen, color, (j, i, gap, gap))
            pygame.display.update()


    def reset(self, seed=None, options=None):
        # Set starting state
        self.state = self.observation_space.sample()
        """
        image = self.state['grid']
        walls = self.state['walls']
        all = self.state['all']
        for i in range(self.len):
            for j in range(self.len):
                image[i][j] = 1
                walls[i][j] = 0
        self.max_area = self.len * self.len-1 #change later
        step = 2
        for i in range(1, self.len-step+1, step):
            for j in range(1, self.len-step+1, step):
                x = i + random.randint(0, step) #wall generation
                y = j + random.randint(0, step)
                image[x][y] = 0
                walls[x][y] = 1
                self.max_area -= 1
                
        for i in range(0, self.len-step, step):
            for j in range(0, self.len-step, step):        
                x = i + random.randint(0, step)#blank generation
                y = j + random.randint(0, step)
                if image[x][y] == 1:
                    self.max_area -= 1
                image[x][y] = 0
                x = i + random.randint(0, step)#blank generation
                y = j + random.randint(0, step)
                if image[x][y] == 1:
                    self.max_area -= 1
                image[x][y] = 0
        """
        self.state['grid'][0] = np.array(grass_data, dtype = np.uint8)
        self.state['grid'][1] = np.array(walls_data, dtype = np.uint8)
        all = self.state['all']
        all[0] = all[1] = 0
        # Set length
        self.running_length = (self.len)*(self.len)
        all[2] = all[5] = 0
        all[3] = all[4] = 1
        all[6], all[7], all[8], all[9] = self.leastDist(all[0], all[1])
        
        all[0+10] = all[1+10] = self.len-1
        # Set length
        self.running_length = (self.len)*(self.len)
        all[2+10] = all[5+10] = 1
        all[3+10] = all[4+10] = 0
        all[6+10], all[7+10], all[8+10], all[9+10] = self.leastDist(all[0+10], all[1+10])                
        self.area_clear = 0
        self.max_area = np.sum(self.state['grid'][0])
        return self.state, {}

    def close(self):
        pass

Env for PPO + normal (optimize later by making symmetry redundant)

In [5]:
class MowerEnv2(Env):
    def __init__(self, info, render_mode = True): #info 0 = len, 1 = number of agents (up to 4)
        self.render_mode = render_mode
        self.len = info[0]
        self.agents = info[1]
        if render_mode == True:
            pygame.init()
            self.screen = pygame.display.set_mode((720, 720))
        # Actions we can up down left right
        self.action_space = MultiDiscrete([4 for i in range(self.agents)])
        # 0=visited, 1=notvisited
        #gym.spaces.space.Space.seed(1)


        self.observation_space = Dict({'grid': Box(low=0, high=1, shape=(2,self.len,self.len), dtype=np.uint8),                       #pos, bounds, guide
                                    'all': Box(low=0, high=self.len-1, shape=(10 * self.agents,), dtype=np.uint8)})

        # Set length
        self.direct = [[-1, 0], [0, 1], [1, 0], [0, -1]]

    def step(self, action):
        reward = 0
        arr = self.state['grid'][0]
        all = self.state['all']
        for j in range(self.agents):
            # Apply action (no walls for now)
            x = all[0 + j * 10] + self.direct[action[j]][0]
            y = all[1 + j * 10] + self.direct[action[j]][1]
            if self.isValid(x, y) == 0:
                x = all[0 + j * 10]
                y = all[1 + j * 10]
            if arr[x][y] == 1:
                self.area_clear += 1
                reward += 5.0 * np.power(4, self.area_clear/self.max_area)
            else:
                reward += -0.5
                self.running_length -= 1
            arr[x][y] = 0
            all[0+j*10] = x
            all[1+j*10] = y

            # update boundries
            for i in range(4):
                all[i+2+j*10] = self.isValid(x + self.direct[i][0], y + self.direct[i][1])
            temp = self.cheats(x, y)
            all[6+j*10]= all[7+j*10]= all[8+j*10]= all[9+j*10] = 0
            for p in temp:
                all[6+j*10+p] = 1
            # Check if  done
            if self.running_length < 0:
                done = True
                break
            else:
                done = False
            if self.finished(): #change back to self.finished()
                print('joyce qu')
                reward += 20 * self.max_area
                done = True
                break
        # Set placeholder for info
        info = {}

        # Return step information
        return (self.state, reward, done, False, info)

    def isValid(self, x, y):
        if x < 0 or x < 0 or x >= self.len or y < 0 or y >= self.len:
            return 0 #return False
        if self.state['grid'][1][x][y] == 1:
            return 0
        return 1 #return true

    def cheats(self, posx, posy):
        if np.sum(self.state['grid'][0]) == 0:
            print('lesgo')
            return [0, 1, 2, 3]
        # Next action:
        # (feed the observation to your agent here)
        made = False
        calc = np.zeros((20, 20))
        list = deque()
        calc[posx][posy] = 1
        list.append([posx, posy])
        move = []
        while True: #has multiple paths issues, but should be irrelevent
            size = len(list)
            for z in range(size):
                tuple = list.popleft()
                for i in range(4):
                    x = tuple[0] + self.direct[i][0]
                    y = tuple[1] + self.direct[i][1]
                    if x >= 0 and x < 20 and y >=0 and y < 20:
                        if self.state['grid'][1][x][y] == 0 and calc[x][y] == 0:
                            calc[x][y] = 1
                            choice = i
                            if len(tuple) == 3:
                                choice = tuple[2]
                            if self.state['grid'][0][x][y] == 0:
                                ret = [x, y, choice]
                                list.append(ret)
                            else:
                                move.append(choice)
                                break

            if len(move) > 0:
                break
        return move

    def leastDist(self, x, y):
        arr = self.state['grid'][0]
        up = right = down = left = 0
        done = False
        for i in range(1, 11):
            for j in range(-i, i+1):
                k = i - abs(j)
                if x + j >=0 and x + j < self.len and y + k < self.len:
                    if arr[x+j][y+k] == 1:
                        done = True
                        down = max(int(k > 0), down)
                        left = max(int(j < 0), left)
                        right = max(int(j > 0), right)
                if x + j >=0 and x + j < self.len and y - k >=0:
                    if arr[x+j][y-k] == 1:
                        done = True
                        up = max(int(k > 0), up)
                        left = max(int(j < 0), left)
                        right = max(int(j > 0), right)
            if done:
                break
        return (up, right, down, left)

    def finished(self):
        return self.area_clear==self.max_area

    def render(self):
        # Implement viz
        if self.render_mode == True:
            pygame.event.get()
            gap = 720//self.len
            arr = self.state['grid'][0]
            pos = self.state['all']
            walls = self.state['grid'][1]
            for i in range(0, 720, gap):
                for j in range(0, 720, gap):
                    if arr[i//gap][j//gap] == 0:
                        color = (255, 255, 255)
                    elif arr[i//gap][j//gap] == 1:
                        color = (255, 255,0)
                    for k in range(self.agents):
                        if pos[0+k*10] == i//gap and pos[1+k*10] == j//gap:
                            color = (255, 0, 0)
                    if walls[i//gap][j//gap] == 1:
                        color = (0, 0, 0)
                    pygame.draw.rect(self.screen, color, (j, i, gap, gap))
            pygame.display.update()

    def perform_sort(self):
        arr = self.state['all']
        for i in range(self.agents):
            for j in range(1, self.agents):
                if (arr[10*i] > arr[10*j]) or ((arr[10*i] == arr[10*j]) and (arr[10*i+1] > arr[10*j+1])):
                    self.do_swap(i, j)
        
    
    def do_swap(self, a, b):
        for i in range(10):
            s = self.state['all'][10*a+i]
            self.state['all'][10*a+i] = self.state['all'][10*b+i]
            self.state['all'][10*b+i] = s
        
    def reset(self, seed=None, options=None):
        # Set starting state
        self.state = self.observation_space.sample()
        """
        image = self.state['grid']
        walls = self.state['walls']
        all = self.state['all']
        for i in range(self.len):
            for j in range(self.len):
                image[i][j] = 1
                walls[i][j] = 0
        self.max_area = self.len * self.len-1 #change later
        step = 2
        for i in range(1, self.len-step+1, step):
            for j in range(1, self.len-step+1, step):
                x = i + random.randint(0, step) #wall generation
                y = j + random.randint(0, step)
                image[x][y] = 0
                walls[x][y] = 1
                self.max_area -= 1

        for i in range(0, self.len-step, step):
            for j in range(0, self.len-step, step):
                x = i + random.randint(0, step)#blank generation
                y = j + random.randint(0, step)
                if image[x][y] == 1:
                    self.max_area -= 1
                image[x][y] = 0
                x = i + random.randint(0, step)#blank generation
                y = j + random.randint(0, step)
                if image[x][y] == 1:
                    self.max_area -= 1
                image[x][y] = 0
        """
        self.state['grid'][0] = np.array(grass_data, dtype = np.uint8)
        self.state['grid'][1] = np.array(walls_data, dtype = np.uint8)
        all = self.state['all']
        for i in range(self.agents):# Set position
            all[0+10*i] = corners[i][0]
            all[1+10*i] = corners[i][1]

            # Set border detect 0 = blocked, 1 = valid
            all[2+10*i] = corners[i][0]
            all[3+10*i] = 1 - corners[i][1]
            all[4+10*i] = 1 - corners[i][0]
            all[5+10*i] = corners[i][1]
            all[6+10*i], all[7+10*i], all[8+10*i], all[9+10*i] = self.leastDist(all[0+10*i], all[1+10*i])

        self.running_length = ((self.len) * (self.len) * (1 + self.agents)) // 2
        self.area_clear = 0
        self.max_area = np.sum(self.state['grid'][0])
        return self.state, {}

    def get_state(self):
        output = []
        for i in range(self.len):
            output.append(np.append(self.state['all'][i*10:i*10+10], np.zeros(4)))
        return (self.state['grid'], output)

    def close(self):
        pass

In [4]:

class CustomCombinedExtractor(BaseFeaturesExtractor):
    def __init__(self, observation_space: spaces.Dict):
        # We do not know features-dim here before going over all the items,
        # so put something dummy for now. PyTorch requires calling
        # nn.Module.__init__ before adding modules
        super().__init__(observation_space, features_dim=1)

        extractors = {}

        total_concat_size = 0
        # We need to know size of the output of this extractor,
        # so go over all the spaces and compute output feature sizes
        for key, subspace in observation_space.spaces.items():
            if key == "grid":
                # We will just downsample one channel of the image by 4x4 and flatten.
                # Assume the image is single-channel (subspace.shape[0] == 0)
                extractors[key] = nn.Sequential(
            nn.Conv2d(2, 64, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.BatchNorm2d(64),
            nn.Conv2d(64, 64, kernel_size=3, stride=1, padding=0),
            nn.ReLU(), #try special max poolings plans
            nn.MaxPool2d(2, 2),
            nn.BatchNorm2d(64),
            nn.Flatten()
        )

                total_concat_size += 4 * 4 * 64 #change later
            else:
                # Run through a simple MLP
                extractors[key] = nn.Linear(subspace.shape[0], 64)
                total_concat_size += 64

        # Now concatenate the obtained features
        self.extractors = nn.ModuleDict(extractors)
        # Update the features dim manually
        self._features_dim = total_concat_size

    def forward(self, observations) -> th.Tensor:
        encoded_tensor_list = []

        # self.extractors contain nn.Modules that do all the processing.
        for key, extractor in self.extractors.items():
            input = observations[key]
                #print(input.shape)
            #print(observations[key])
            #print(observations[key].shape)
            thing = extractor(input)
            encoded_tensor_list.append(thing)
            #print(observations[key].shape)
            #print(extractor(observations[key]))
        # Return a (B, self._features_dim) PyTorch tensor, where B is batch dimension.
        #print(encoded_tensor_list[0].shape)
        #print(encoded_tensor_list[1].shape)
        #print(encoded_tensor_list[2].shape)
        return th.cat(encoded_tensor_list, dim=1)

In [6]:
#env = MowerEnv(36, True)
env = MowerEnv2([20, 4], True)
env.reset()

(OrderedDict([('all',
               array([ 0,  0,  0,  1,  1,  0,  0,  1,  1,  0, 19, 19,  1,  0,  0,  1,  1,
                       0,  0,  1, 19,  0,  1,  1,  0,  0,  0,  0,  1,  0,  0, 19,  0,  0,
                       1,  1,  1,  1,  0,  0], dtype=uint8)),
              ('grid',
               array([[[0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0],
                       [1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0],
                       [1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0],
                       [0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0],
                       [0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
                       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0],
                       [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1],
                       [0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
                       [0, 0, 0, 

In [7]:
check_env(env)

c:\Users\ziduo\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\common\env_checker.py:38: UserWarning: It seems that your observation space grid is an image but the upper and lower bounds are not in [0, 255]. Because the CNN policy normalize automatically the observation you may encounter issue if the values are not in that range.
  warnings.warn(
c:\Users\ziduo\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\common\env_checker.py:51: UserWarning: The minimal resolution for an image is 36x36 for the default `CnnPolicy`. You might need to use a custom features extractor cf. https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html
  warnings.warn(


In [8]:
model = DQN("MultiInputPolicy", env, gamma = 0.999,buffer_size=100000, verbose=1, tau = 0.1, batch_size = 64, exploration_fraction=0.95, exploration_final_eps=0.15, seed=111, _init_setup_model = True,policy_kwargs=dict(features_extractor_class=CustomCombinedExtractor,activation_fn=nn.ReLU, net_arch = [128, 64, 32]))

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


AssertionError: The algorithm only supports (<class 'gymnasium.spaces.discrete.Discrete'>,) as action spaces but MultiDiscrete([4 4 4 4]) was provided

In [31]:
model = PPO("MultiInputPolicy", env,gamma=0.999, learning_rate = 0.0001, verbose = 1, seed = 111, ent_coef = 0.001, policy_kwargs=dict(features_extractor_class=CustomCombinedExtractor, net_arch=dict(pi=[128, 64, 64], vf=[128, 64, 64]), activation_fn=nn.ReLU, optimizer_class = Adam, normalize_images=False)) #try and make activations not relu

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [52]:
path2 = os.path.join('C:\\', 'Users', 'ziduo', 'Python',  'Training', 'Saved_Models', 'new_thing')
print(path2)


C:\Users\ziduo\Python\Training\Saved_Models\new_thing


In [13]:
model = PPO.load(path2, env )

NameError: name 'path2' is not defined

In [35]:
model.learn(total_timesteps=2000000, log_interval = 2, reset_num_timesteps=False)

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 526         |
|    ep_rew_mean          | 1.41e+03    |
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 2           |
|    time_elapsed         | 18          |
|    total_timesteps      | 700694      |
| train/                  |             |
|    approx_kl            | 0.022767905 |
|    clip_fraction        | 0.223       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.778      |
|    explained_variance   | 0.947       |
|    learning_rate        | 0.0001      |
|    loss                 | 115         |
|    n_updates            | 3410        |
|    policy_gradient_loss | -0.00533    |
|    value_loss           | 840         |
-----------------------------------------
lesgo
joyce qu
lesgo
joyce qu
-----------------------------------------
| rollout/                |             |
|   

KeyboardInterrupt: 

In [62]:
#log_path2 = os.path.join('Training', 'Saved Models', 'PPO_thing')
#path2 = os.path.join('C:', 'Users', 'ziduo', 'Python',  'Training', 'Saved_Models', 'new_thing')
model.save('./models/saved_test.zip')

IndexError: tuple index out of range

In [18]:
pygame.quit()

In [42]:


best = 0 #around 19% success rate
low = 100000
for i in range(500):
    obs, _ = env.reset()
    average = 0
    length = 0
    while True:
        # Next action:
        # (feed the observation to your agent here)
        action = model.predict(obs)

        # Processing:
        obs, reward, terminated, _, info = env.step(action[0])
        average += reward
        length += 1
        # Rendering the game:
        # (remove this two lines during training)
        #env.render()
        #time.sleep(1 / 10)  # FPS
        
        # Checking if the player is still alive
        if terminated:
            break
    best = max(best, average)
    if average > 3000:
        low = min(low, length)
print(length)
print(best)

lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
lesgo
joyc

In [8]:
simulate = MowerEnv2([20, 4], True)
simulate.reset()

(OrderedDict([('all',
               array([ 0,  0,  0,  1,  1,  0,  0,  1,  1,  0, 19, 19,  1,  0,  0,  1,  1,
                       0,  0,  1, 19,  0,  1,  1,  0,  0,  0,  0,  1,  0,  0, 19,  0,  0,
                       1,  1,  1,  1,  0,  0], dtype=uint8)),
              ('grid',
               array([[[0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0],
                       [1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0],
                       [1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0],
                       [0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0],
                       [0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
                       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0],
                       [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1],
                       [0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
                       [0, 0, 0, 

In [12]:
obs, _ = simulate.reset()
while True:
    # Next action:
    # (feed the observation to your agent here)
    made = False
    simulate.render()
    time.sleep(1 / 60)  # FPS
    while not made:
        for event in pygame.event.get():
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_UP:
                    action = 0
                    made= True
                elif event.key == pygame.K_RIGHT:
                    action = 1
                    made= True
                elif event.key == pygame.K_DOWN:
                    action = 2
                    made= True
                elif event.key == pygame.K_LEFT:
                    action = 3
                    made= True
                

    # Processing:
    obs, reward, terminated, _, info = simulate.step(action)
    # Rendering the game:
    # (remove this two lines during training)
    
    # Checking if the player is still alive
    if terminated:
        break

env.close()

TypeError: 'int' object is not subscriptable

In [43]:
list = [1,1,2,3,2,2,2,2,2,0,2,0,2,2,1,2,1,1,1,2,3,2,1,2,1,1,0,1,1,0,1,0,0,1,1,0,3,3,1,0,0,1,2,3,1,2,0,2,1,0,1,1,0,1,0,3,2,2,2,2,1,2,2,2,2,1,2,2,2,2,3,3,2,2,3,2,0,2,2,2,2,2,2,1,1,2,3,1,1,3,1,3,1,2,1,1,1,0,1,3,1,1,3,0,1,0,1,0,0,1,1,1,1,2,1,2,1,1,2,1,3,3,2,3,2,3,2,2,1,1,1,3,1,1,0,2,2,2,2,2,3,0,3,3,0,3,0,2,3,3,0,2,1,2,2,1,2,2,1,2,1,1,1,1,1,2,1,2,2,1,0,1,1,2,0,0,0,0,0,0,0,2,3,2,2,2,2,0,1,3,2,0,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,2,0,1,3,1,3,1,3,1,0,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,2,1,3,1,0,3,1,3,1,3,1,3,1,3,1,3,1,0,3,1,3,1,3,1,3,1,3,2,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,3,1,3,1,3,1,3,1,2,3,1,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,2,1,3,0,1,3,1,2,0,3,1,3,1,3,2,0,2,0,0,1,3,1,3,0,1,3,1,3,1,3,1,3,1,3,1,3,0,1,3,1,0,3,1,3,1,3,1,3,1,3,1,0,0,0,3,3,3,1,0,3,0,0,0,0,0,0,0,3,1,3,0,0,0,3,3,2,2,2,2,3,3,0,3,1,1,0,2,2,2,2,2,0,2,2,2,2,2,1,2,1,2,2,1,2,2,1,1,2,0,0,0,2,0,2,0,3,0,1,2,0,3,0,0,3,0,3,3,2,0,3,2,0,2,0,2,0,2,3,2,0,2,0,2,0,0,2,0,2,3,0,0,0,3,3,0,2,0,3,3,3,2,2,3,2,0,3,3,2,3,3,3,0,2,2,1,3,0,2,3,2,2,2,3,2,0,3,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,3,3,3,2,3,3,3,2,2,2,1,2,3,1,2,3,2,3,3,3,3,3,3,3,0,3,0,0,0,0,1,1,2,1,2,2,1,2,1,1,0,2,3,2,0,2,0,3,0,0,1,0,1,2,0,0,3,3,2,0,3,0,3,0,1,3,0,0,0,3,2,3,2,2,1,1,0,0,1,1,2,2,1,0,1,2,3,0,1,1,1,1,0,0,3,1,3,3,1,0,1,1,1,0,1,0,0,0,3,3,2,2,0,0,1,1,1,0,1,2,1,0,2,2,2,3,2,3,2,0,2,0,2,3,0,2,0,2,0,2,3,0,2,0,0,2,0,2,0,1,3,2,0,2,0,2,0,2,2,0,2,0,2,0,0,2,0,2,0,2,2,0,2,0,2,0,0,2,0,2,0,2,0,2,0,2,0,2,2,0,2,3,0,2,0,2,0,2,2,3,0,2,0,3,0,2,0,2,0,3,2,0,2,2,3,3,0,2,3,2,3,2,3,2,3,2,2,1,2,2,3,1,3,3,3,2,1,2,2,2,3,1,1,3,1,3,1,2,1,1,0,1,2,2,2,2,1,1,0,2,1,3,1,1,1,0,0,0,0,0,0,0,0,0,3,0,3,2,1,0,0,3,2,0,0,1,0,1,0,2,1,1,0,0,2,0,2,0,2,0,2,0,2,0,2,1,0,2,0,2,0,2,0,2,1,3,0,2,2,2,2,1,3,0,0,0,1,0,1,2,0,0,1,1,1,1,0,0,2,0,1,1,3,2,2,0,2,1,0,0,2,0,1,3,2,2,2,0,0,2,0,0,2,0,2,0,2,0,2,0,2,0,2,0,2,0,1,3,2,0,2,0,2,0,2,0,2,0,0,2,0,2,0,2,0,2,3,0,2,0,2,0,2,0,0,2,0,2,0,2,0,2,0,2,0,2,0,2,0,2,1,0,3,1,1,3,2,0,2,0,2,0,2,0,2,0,2,0,3,2,0,0,1,0,0,0,3,2,2,0,0,2,0,0,2,0,1,0,2,1,3,3,3,3,3,0,0,1,0,0,3,0,3,2,2,1,1,1,1,1,0,1,0,0,0,1,0,0,1,2,0,0,1,0,1,1,0,0,1,1,0,1,0,0,3,3,3,1,3,1,3,3,3,3,3,3,2,3,0,3,3,3,3,3,3,3,3,2,0,3,3,3,2,2,2,3,1,0,1,0,1,1,1,1,1,2,2,2,2,0,2,3,1,2,1,1,2,1,0,1,3,2,1,3,0,1,0,0,0,0,3,3,2,1,1,1,2,0,2,1,0,2,1,2,3,3,0,1,2,2,3,1,3,1,3,1,3,0,1,2,1,0,0,0,0,3,0,1,3,1,1,0,1,0,2,0,2,3,2,0,1,3,1,3,1,2,0,3,1,3,1,3,1,3,0,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,0,1,2,3,1,3,1,3,1,3,1,3,1,2,0,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,3,1,1,3,1,3,1,3,2,0,1,3,2,0,1,3,1,3,1,3,1,3,0,0,1,3,1,3,1,3,3,1,1,3,0,1,3,1,1,1,2,3,3,3,3,2,2,2,3,0,2,2,1,3,2,3,2,2,2,2,3,0,0,3,3,0,1,3,1,3,1,3,1,3,1,3,1,3,1,3,3,1,3,3,1,3,1,3,1,3,2,3,3,3,3,3,3,3,3,3,3,2,3,1,2,2,2,2,2,0,2,2,2,2,3,1,3,3,1,2,3,3,2,3,2,3,1,3,2,0,0,3,3,0,3,3,2,0,3,3,3,0,3,2,3,2,2,1,3,3,1,0,0,0,0,3,3,2,3,0,3,0,0,2,0,1,0,3,1,3,0,2,3,3,3,0,0,2,0,0,1,0,0,3,0,3,3,2,3,2,2,2,2,0,0,1,3,2,2,2,0,2,0,2,1,1,2,1,3,1,0,3,2,1,3,2,3,3,1,2,2,2,1,2,1,0,1,2,1,3,3,1,2,2,1,1,0,2,3,2,3,1,3,1,3,1,3,1,3,1,2,2,3,2,3,1,3,1,3,1,3,0,1,1,3,1,2,3,1,3,3,1,1,0,1,0,2,3,1,2,3,0,0,3,0,2,0,0,0,3,0,3,3,3,2,2,2,0,2,0,2,0,2,0,0,2,2,0,2,0,2,0,2,2,1,1,2,0,1,1,1,1,2,0,1,1,1,2,0,1,2,0,1,3,0,0,2,0,3,0,1,3,2,0,3,1,3,1,3,1,3,1,3,1,3,0,1,1,1,0,0,1,1,1,1,2,0,3,1,2,0,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,3,1,1,0,0,0,2,3,1,3,1,3,1,3,3,1,3,1,3,1,3,1,1,3,0,3,1,1,3,1,3,1,3,1,1,3,1,3,1,3,3,1,3,1,3,1,3,3,3,1,2,3,0,1,3,1,1,1,3,1,3,2,0,1,3,1,3,0,0,1,0,0,3,0,2,3,3,0,0,1,3,0,2,3,3,1,1,2,0,1,0,1,2,2,0,3,0,0,3,0,0,2]

In [44]:
print(len(list)-36*36)
print(np.sum(grass_data))

408
546.0


In [8]:
obs, _ = simulate.reset()
step = 0
while True:
    # Next action:
    # (feed the observation to your agent here)
    made = False
    simulate.render()
    time.sleep(1 / 60)  # FPS
    action = list[step]
    step +=1

    # Processing:
    obs, reward, terminated, _, info = simulate.step(action)
    # Rendering the game:
    # (remove this two lines during training)
    
    # Checking if the player is still alive
    if terminated:
        break

env.close()

TypeError: list[0] is not a generic class

Auto Solver

In [12]:
dir = [[-1, 0], [0, 1], [1, 0], [0, -1]]
obs, _ = simulate.reset()
step = 0
while True:
    # Next action:
    # (feed the observation to your agent here)
    made = False
    action = []
    for i in range(4):
        calc = np.zeros((20, 20))
        list = deque()
        list.append([obs['all'][0+10*i], obs['all'][1+10*i]])
        calc[obs['all'][0+10*i]][obs['all'][1+10*i]] = 1
        move = -1
        while True:
            tuple = list.popleft()
            for i in range(4):
                x = tuple[0] + dir[i][0]
                y = tuple[1] + dir[i][1]
                if x >= 0 and x < 20 and y >=0 and y < 20:
                    if obs['grid'][1][x][y] == 0 and calc[x][y] == 0:
                        calc[x][y] = 1
                        choice = i
                        if len(tuple) == 3:
                            choice = tuple[2]
                        if obs['grid'][0][x][y] == 0:
                            ret = [x, y, choice]
                            list.append(ret)
                        else:
                            move = choice
                            break
            if move != -1:
                break
        action.append(move)
        
    
    time.sleep(1 / 30)  # FPS
    
    step +=1

    # Processing:
    obs, reward, terminated, _, info = simulate.step(action)
    simulate.render()
    # Rendering the game:
    # (remove this two lines during training)
    
    # Checking if the player is still alive
    if terminated:
        break
print(step)
print(reward)
env.close()

lesgo
joyce qu
lesgo
joyce qu
lesgo
joyce qu
117
3260


In [33]:
ret = [5, 6]
if len(ret) == 2:
    ret += [2]
print(ret)

[5, 6, 2]
